import { AiOutlineMobile } from 'react-icons/ai'
import { BsHouseDoor } from 'react-icons/bs'
import { FiMonitor } from 'react-icons/fi'
import { FaDog } from 'react-icons/fa'
import { BiCar, BiBed } from 'react-icons/bi'
import { RiMotorbikeLine, RiTShirt2Line } from 'react-icons/ri'
import { IoMdBusiness } from 'react-icons/io'
import { GiTennisRacket } from 'react-icons/gi'
import { GrServices } from 'react-icons/gr'
import { MdBusinessCenter, MdChildFriendly } from 'react-icons/md'
// https://www.olx.com.pk/payments/packages/consume/free/success
const noUser = {
    userPrimary: "https://firebasestorage.googleapis.com/v0/b/sellit-928cd.appspot.com/o/images%2Fuser.jpg?alt=media&token=74e7ace2-9099-4b13-9167-edc90d4bc9e4",
    userSecondary: "https://firebasestorage.googleapis.com/v0/b/sellit-928cd.appspot.com/o/images%2Fuser%20-%20secondary.png?alt=media&token=c1ce91af-9ae3-4b48-a1ce-a49c9586d4eb"
}
const noAd = {
    adImage: 'https://statics.olx.com.pk/olxpk/misc/emptyState_v1.png'
}
const categories = {
    "Mobiles": AiOutlineMobile,
    "Vehicles": BiCar,
    "Property": BsHouseDoor,
    "Electronics & Home Appliances": FiMonitor,
    "Bikes": RiMotorbikeLine,
    "Business, Industrial & Agriculture": IoMdBusiness,
    "Services": GrServices,
    "Jobs": MdBusinessCenter,
    "Animals": FaDog,
    "Furniture & Home Decor": BiBed,
    "Fashion & Beauty": RiTShirt2Line,
    "Books, Sports & Hobbies": GiTennisRacket,
    "Kids": MdChildFriendly
}
const cities = [
    "Karachi",
    "Lahore",
    "Faisalabad",
    "Serai",
    "Rawalpindi",
    'Multan',
    "Gujranwala",
    "Hyderabad",
    "Peshawar",
    "Abbottabad",
    "Islamabad",
    "Quetta",
    "Bannu",
    "Bahawalpur",
    "Sargodha",
    "Sialkot",
    "Sukkur",
    "Larkana",
    "Sheikhupura",
    "Mirpur Khas",
    "Rahimyar Khan",
    "Kohat",
    "Jhang Sadr",
    "Gujrat",
    "Bardar",
    "Kasur",
    "Dera Ghazi Khan",
    "Masiwala",
    "Nawabshah",
    "Okara",
    "Gilgit",
    "Chiniot",
    "Sadiqabad",
    "Turbat",
    "Dera Ismail Khan",
    "Chaman",
    "Zhob",
    "Mehra",
    "Parachinar",
    "Gwadar",
    "Kundian",
    "Shahdad Kot",
    "Haripur",
    "Matiari",
    "Dera Allahyar",
    "Lodhran",
    "Batgram",
    "Thatta",
    "Bagh",
    "Badin",
    "Mansehra",
    "Ziarat",
    "Muzaffargarh",
    "Tando Allahyar",
    "Dera Murad Jamali",
    "Karak",
    "Mardan",
    "Uthal",
    "Nankana Sahib",
    "Barkhan",
    "Hafizabad",
    "Kotli",
    "Loralai",
    "Dera Bugti",
    "Jhang",
    "Sahiwal",
    "Sanghar",
    "Pakpattan",
    'Chakwal',
    "Khushab",
    'Ghotki',
    "Kohlu",
    "Khuzdar",
    "Awaran",
    "Nowshera",
    "Charsadda",
    "Qila Abdullah",
    "Bahawalnagar",
    "Dadu",
    "Aliabad",
    "Lakki Marwat",
    "Chilas",
    "Pishin",
    "Tank",
    "Chitral",
    "Qila Saifullah",
    "Shikarpur",
    "Panjgur",
    "Mastung",
    "Kalat",
    'Gandava',
    "Khanewal",
    "Narowal",
    "Khairpur",
    "Malakand",
    "Vihari",
    "Saidu Sharif",
    "Jhelum",
    "Mandi Bahauddin",
    "Bhakkar",
    "Toba Tek Singh",
    "Jamshoro",
    "Kharan",
    "Umarkot",
    "Hangu",
    "Timargara",
    'Gakuch',
    "Jacobabad",
    'Alpurai',
    'Mianwali',
    "Musa Khel Bazar",
    "Naushahro Firoz",
    "New Mirpur",
    "Daggar",
    "Eidgah",
    'Sibi',
    "Dalbandin",
    'Rajanpur',
    "Leiah",
    "Upper Dir",
    "Tando Muhammad Khan",
    "Attock",
    "Rawala Kot",
    "Swabi",
    "Kandhkot",
    "Dasu"
]
export { noUser, noAd, categories, cities }